export const ADD_CAR_REQ="ADD_CAR_REQ"
export const ADD_CAR_SUCCESS="ADD_CAR_SUCCESS"
export const ADD_CAR_FAIL="ADD_CAR_FAIL"

export const GET_CAR_REQ="GET_CAR_REQ"
export const GET_CAR_SUCCESS="GET_CAR_SUCCESS"
export const GET_CAR_FAIL="GET_CAR_FAIL"